# Generated by Django 5.0.6 on 2025-04-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='impreso',
            field=models.BooleanField(default=False),
        ),
    ]
