# Generated by Django 5.0.6 on 2025-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido_impreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='impreso',
            field=models.BooleanField(default=False, verbose_name='Ticket impreso'),
        ),
    ]
