# Generated by Django 5.0.6 on 2025-04-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_mp_merchant_order_id_pedido_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mp_merchant_order_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mp_payment_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mp_preference_id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('en_preparacion', 'En preparación'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
