# Generated by Django 5.0.6 on 2025-04-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_pedido_mp_merchant_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
