# Generated by Django 5.0.6 on 2025-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_agotado_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='whatsapp_business_id',
            field=models.CharField(blank=True, help_text='ID de WhatsApp Business', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='whatsapp_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones WhatsApp'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ej: +541234567890', max_length=20, null=True),
        ),
    ]
