# Generated by Django 5.0.6 on 2025-04-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_restaurante_whatsapp_business_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='whatsapp_business_id',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='whatsapp_notifications',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='whatsapp_verified',
        ),
    ]
