# Generated by Django 5.0.6 on 2025-04-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pedido_motivo_cancelacion_pedido_tiempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_cancelado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_en_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('en_preparacion', 'En preparación'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('archivado', 'Archivado')], default='pendiente', max_length=20),
        ),
    ]
