# Generated by Django 5.0.6 on 2025-04-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pedido_fecha_cancelado_pedido_fecha_en_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
