# Generated by Django 5.0.6 on 2025-04-11 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='tiempo_demora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo estimado de demora (ej. 15-30 minutos)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='tiene_demora',
            field=models.BooleanField(default=False, verbose_name='¿Hay demora en los pedidos?'),
        ),
        migrations.CreateModel(
            name='HorarioRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_apertura', models.TimeField(verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de cierre')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario del Restaurante',
                'verbose_name_plural': 'Horarios del Restaurante',
                'ordering': ['dia_semana', 'hora_apertura'],
            },
        ),
    ]
