# Generated by Django 5.0.6 on 2025-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_restaurante_tiempo_demora_restaurante_tiene_demora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='cerrado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Cerrar manualmente el restaurante'),
        ),
    ]
