# Generated by Django 5.0.6 on 2025-04-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_restaurante_cerrado_manualmente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='cerrado_manualmente',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='estado_control',
            field=models.CharField(choices=[('cerrado', 'Cerrado'), ('automatico', 'Automático (según horarios)'), ('abierto', 'Abierto')], default='automatico', max_length=10, verbose_name='Control de estado del restaurante'),
        ),
    ]
