# Generated by Django 5.0.6 on 2025-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_restaurante_cerrado_manualmente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='codigos_descuento',
            field=models.JSONField(blank=True, default=list, verbose_name='Códigos de descuento'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de envío fijo'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='umbral_envio_gratis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto mínimo para envío gratis'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='tiempo_demora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo estimado de demora'),
        ),
    ]
