# Generated by Django 5.0.6 on 2025-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_restaurante_codigos_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_descuento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de descuento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto del descuento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('en_preparacion', 'En preparación'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('archivado', 'Archivado'), ('en_entrega', 'En entrega')], default='pendiente', max_length=20),
        ),
    ]
