# Generated by Django 5.0.6 on 2025-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_itempedido_opciones_seleccionadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionproducto',
            name='agotado',
            field=models.BooleanField(default=False, verbose_name='Agotado'),
        ),
    ]
