# Generated by Django 5.0.6 on 2025-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_opcionproducto_agotado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('retiro', 'Retiro en Local')], default='retiro', max_length=20),
        ),
    ]
