# Generated by Django 5.0.6 on 2025-04-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0025_pedido_tipo_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurante',
            options={},
        ),
        migrations.AddField(
            model_name='restaurante',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Usuario de Facebook'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Usuario de Instagram'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Palabras Clave (SEO, separadas por comas)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='written_schedules',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Horarios Escritos (ej. Lunes a Viernes 12:00-22:00)'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='restaurante',
            index=models.Index(fields=['username', 'activo'], name='core_restau_usernam_bd3dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurante',
            index=models.Index(fields=['meta_title'], name='core_restau_meta_ti_d86a33_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurante',
            index=models.Index(fields=['meta_keywords'], name='core_restau_meta_ke_bd31e1_idx'),
        ),
    ]
