# Generated by Django 5.0.6 on 2025-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_restaurante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_descuento',
            field=models.BooleanField(default=False),
        ),
    ]
