# Generated by Django 5.0.6 on 2025-04-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_producto_precio_original_producto_tiene_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='categorias_banners/'),
        ),
    ]
