# Generated by Django 5.0.6 on 2025-04-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_categoria_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='opcionproducto',
            name='precio_adicional_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opcionproducto',
            name='tiene_descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OpcionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('max_selecciones', models.PositiveIntegerField(default=1, help_text='Número máximo de opciones que se pueden seleccionar en esta categoría')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcion_categorias', to='core.producto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='opcionproducto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.opcioncategoria'),
        ),
    ]
