# Generated by Django 5.0.6 on 2025-04-29 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_opcionproducto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.opcioncategoria'),
        ),
    ]
