# Generated by Django 5.0.6 on 2025-04-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_opcionproducto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionproducto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='opcionproducto',
            name='precio_adicional_original',
        ),
        migrations.AlterField(
            model_name='opcionproducto',
            name='tiene_descuento',
            field=models.BooleanField(default=False, verbose_name='Aplicar descuento del producto'),
        ),
    ]
