# Generated by Django 5.0.6 on 2025-04-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_opcionproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionproducto',
            name='precio_adicional_con_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Adicional con Descuento'),
        ),
    ]
