# Generated by Django 5.0.6 on 2025-04-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_opcionproducto_precio_adicional_con_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionproducto',
            name='precio_adicional_con_descuento',
        ),
    ]
