# Generated by Django 5.0.6 on 2025-04-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_opcionproducto_precio_adicional_con_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionproducto',
            name='precio_adicional_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
