# Generated by Django 5.0.6 on 2025-05-02 13:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_opcionproducto_precio_adicional_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_restaurante_media_path),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_restaurante_media_path),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_restaurante_media_path),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['restaurante', 'nombre'], name='core_catego_restaur_57c025_idx'),
        ),
    ]
