# Generated by Django 5.2.1 on 2025-05-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_restaurante_cash_discount_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cash_discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cash_discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
