# Generated by Django 5.2.1 on 2025-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_pedido_cash_discount_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal'),
        ),
    ]
