# Generated by Django 5.2.1 on 2025-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_pedido_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notification_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
