# Generated by Django 5.2.1 on 2025-05-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_restaurante_notification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='notification_token',
        ),
    ]
