# Generated by Django 5.2.1 on 2025-05-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_restaurante_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='notification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
