# Generated by Django 5.2.1 on 2025-05-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_restaurante_notification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurante',
            options={'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
    ]
