# Generated by Django 5.2.1 on 2025-05-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_restaurante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurante',
            options={},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='notification_token',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='notification_token',
        ),
    ]
