# Generated by Django 5.2.1 on 2025-05-16 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_restaurante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcioncategoria',
            name='max_selecciones',
            field=models.PositiveIntegerField(default=1, help_text='Númerodoğan de opciones que se pueden seleccionar en esta categoría'),
        ),
        migrations.AlterField(
            model_name='opcionproducto',
            name='precio_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
