# Generated by Django 5.2.1 on 2025-05-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_opcioncategoria_max_selecciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionproducto',
            name='precio_adicional_original',
        ),
    ]
