# Generated by Django 5.2.1 on 2025-05-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_opcionproducto_precio_adicional_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionproducto',
            name='precio_adicional_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
