# Generated by Django 5.2 on 2025-05-27 HH:MM
from django.db import migrations, models
import uuid

def generate_unique_tokens(apps, schema_editor):
    Pedido = apps.get_model('core', 'Pedido')
    for pedido in Pedido.objects.filter(token__isnull=True):
        pedido.token = uuid.uuid4()
        pedido.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_opcionproducto_precio_adicional_original'),  # Replace with the actual previous migration name
    ]

    operations = [
        # Step 1: Add the token field as nullable (no unique constraint yet)
        migrations.AddField(
            model_name='Pedido',
            name='token',
            field=models.UUIDField(null=True, editable=False, verbose_name='Token de acceso'),
        ),
        # Step 2: Run a data migration to populate token for existing records
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        # Step 3: Alter the field to add the unique constraint and make it non-nullable
        migrations.AlterField(
            model_name='Pedido',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de acceso'),
        ),
    ]