# Generated by Django 5.2.1 on 2025-05-28 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_pedido_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['token'], name='core_pedido_token_5a5b13_idx'),
        ),
    ]
