# Generated by Django 5.2.1 on 2025-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_pedido_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del restaurante', max_length=100, unique=True)),
                ('qr_image', models.ImageField(blank=True, help_text='Imagen del QR generada', null=True, upload_to='qrcodes/')),
                ('url', models.URLField(blank=True, help_text='URL asociada al QR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
