# Generated by Django 5.2.1 on 2025-07-15 16:49

import core.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_restaurantqr_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.MediaStorage(), upload_to=core.models.get_restaurante_media_path),
        ),
    ]
