# Generated by Django 5.2.1 on 2025-07-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_payment_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_procesando_pago',
            new_name='fecha_error_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='error_pago_mensaje',
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_error_pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='core_pedido_estado_404470_idx'),
        ),
    ]
