# Generated by Django 5.2.1 on 2025-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_rename_fecha_procesando_pago_pedido_fecha_error_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='payment_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
