# Generated by Django 5.2.1 on 2025-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_pedido_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='init_point',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='color_principal',
            field=models.CharField(default='#f85c2b', max_length=7),
        ),
    ]
