# Generated by Django 5.2.1 on 2025-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_pedido_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='mp_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Mercado Pago Access Token'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='mp_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Mercado Pago Refresh Token'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='mp_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mercado Pago Token Expiration'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='mp_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mercado Pago User ID'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='color_principal',
            field=models.CharField(default='#f85c2b', max_length=7),
        ),
    ]
