# Generated by Django 5.2.1 on 2025-10-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_restaurante_mp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='alias_cbu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias/CBU para transferencias'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='metodo_pago_alias',
            field=models.BooleanField(default=False, verbose_name='Habilitar Pago por Alias'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='metodo_pago_mercadopago',
            field=models.BooleanField(default=True, verbose_name='Habilitar Mercado Pago'),
        ),
    ]
