# Generated by Django 5.2.1 on 2025-10-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_restaurante_alias_cbu_restaurante_metodo_pago_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='google_verification_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de verificación de Google'),
        ),
    ]
